-- Final Schema Dump (v1.0) - Dormichan Dormitory Management System
-- Generated: 2026-02-11
-- This file represents the consolidated schema for production launch.

-- 1. Enable Realtime
alter publication supabase_realtime add table room_assignments;
alter publication supabase_realtime add table leave_requests;
alter publication supabase_realtime add table notifications;
alter publication supabase_realtime add table points_log;

-- 2. Tables

-- Students Table
CREATE TABLE IF NOT EXISTS public.students (
    student_id text NOT NULL PRIMARY KEY,
    name text NOT NULL,
    grade integer NOT NULL,
    class integer NOT NULL,
    number integer NOT NULL,
    gender text CHECK (gender IN ('M', 'F')),
    bonus_points integer DEFAULT 0,
    minus_points integer DEFAULT 0,
    cleaning_points integer DEFAULT 0,
    password text,
    is_monitor boolean DEFAULT false
);

-- Teachers Table
CREATE TABLE IF NOT EXISTS public.teachers (
    teacher_id text NOT NULL PRIMARY KEY,
    name text NOT NULL,
    position text DEFAULT '교사', -- '사감', '기숙사부장', '관리자'
    phone text,
    password text
);

-- Room Assignments Table
CREATE TABLE IF NOT EXISTS public.room_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id text REFERENCES public.students(student_id) ON DELETE CASCADE,
    room_number integer NOT NULL,
    seat_number integer, -- 1 (Left), 2 (Right)
    floor integer NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(student_id)
);

-- Leave Requests Table
CREATE TABLE IF NOT EXISTS public.leave_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id text REFERENCES public.students(student_id) ON DELETE CASCADE,
    type text NOT NULL, -- '외출', '외박', '귀가', '이동'
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    reason text,
    status text DEFAULT 'pending', -- 'pending', 'approved', 'rejected', 'cancelled'
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Notifications Table
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id text NOT NULL, -- teacher_id or student_id
    title text NOT NULL,
    message text NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Points Log Table
CREATE TABLE IF NOT EXISTS public.points_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id text REFERENCES public.students(student_id) ON DELETE CASCADE,
    type text NOT NULL, -- 'bonus', 'minus', 'cleaning'
    points integer NOT NULL,
    reason text,
    recorded_by text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Row Level Security (RLS) Policies

-- Students: Public Read, Self Update (for password?) - Actually restricted updates usually.
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public students are viewable by everyone" ON public.students FOR SELECT USING (true);
-- (Add specific update policies if needed, currently keeping open for dev or specific strict policies)

-- Teachers: Public Read
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public teachers are viewable by everyone" ON public.teachers FOR SELECT USING (true);

-- Room Assignments: Public Read, Teacher Update
ALTER TABLE public.room_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Room assignments are viewable by everyone" ON public.room_assignments FOR SELECT USING (true);
CREATE POLICY "Teachers can insert room assignments" ON public.room_assignments FOR INSERT WITH CHECK (auth.role() = 'anon'); -- Simplified for local dev, strict RLS needs auth.uid() check against teachers table
CREATE POLICY "Teachers can update room assignments" ON public.room_assignments FOR UPDATE USING (true);
CREATE POLICY "Teachers can delete room assignments" ON public.room_assignments FOR DELETE USING (true);

-- Leave Requests: Public Read (for Status Board), Student Insert, Teacher Update
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Leave requests are viewable by everyone" ON public.leave_requests FOR SELECT USING (true);
CREATE POLICY "Students can insert leave requests" ON public.leave_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Teachers can update leave requests" ON public.leave_requests FOR UPDATE USING (true);

-- 4. Indexes (Performance)
CREATE INDEX IF NOT EXISTS idx_students_grade_class ON public.students(grade, class);
CREATE INDEX IF NOT EXISTS idx_room_assignments_room_number ON public.room_assignments(room_number);
CREATE INDEX IF NOT EXISTS idx_leave_requests_student_id ON public.leave_requests(student_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_status ON public.leave_requests(status);
