-- [해결 방법]
-- 에러 원인: students 테이블의 'student_id(학번)'이 고유값(Unique)으로 설정되어 있지 않아서, 다른 테이블에서 참조할 수 없었습니다.
-- 아래 명령어를 순서대로 실행하면 해결됩니다.

-- 1. 먼저 students 테이블의 student_id에 '고유값 제한'을 추가합니다.
-- (주의: 만약 이미 중복된 학번이 학생 데이터에 들어있다면 이 단계에서 에러가 납니다. 그럴 경우 중복된 학생을 먼저 삭제해야 합니다.)
ALTER TABLE students ADD CONSTRAINT students_student_id_unique UNIQUE (student_id);


-- 2. 열람실 구조 테이블 생성
create table if not exists room_layouts (
  room_number int primary key,
  columns int not null default 6,
  total_seats int not null default 30,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. 좌석 배정 테이블 생성 (이제 참조가 가능합니다)
create table if not exists seat_assignments (
  id bigint generated by default as identity primary key,
  room_number int not null,
  seat_number int not null,
  student_id text not null references students(student_id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint unique_seat unique (room_number, seat_number)
);

-- 4. 권한 설정
alter table room_layouts enable row level security;
alter table seat_assignments enable row level security;

create policy "Allow all access to room_layouts" on room_layouts for all using (true) with check (true);
create policy "Allow all access to seat_assignments" on seat_assignments for all using (true) with check (true);
