-- 관리자 대시보드용 추가 테이블 생성

-- 1. 시설 보수 요청 (Facility Requests)
create table if not exists facility_requests (
  id bigint generated by default as identity primary key,
  title text not null, -- 예: "305호 에어컨 고장"
  description text,
  status text not null default '대기', -- 대기, 진행중, 완료
  reporter_id text, -- 신고자 (선생님 ID 등)
  room_number int, -- 관련 호실 (옵션)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 환자 관리 (Patients)
create table if not exists patients (
  id bigint generated by default as identity primary key,
  student_id text not null references students(student_id) on delete cascade,
  symptom text not null, -- 예: "두통", "발목 염좌"
  status text not null default '기숙사', -- 기숙사, 입원, 귀가
  note text, -- 비고 (처방약 등)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  resolved_at timestamp with time zone -- 완치/해제 시각
);

-- 권한 설정 (RLS)
alter table facility_requests enable row level security;
alter table patients enable row level security;

create policy "Allow all access to facility_requests" on facility_requests for all using (true) with check (true);
create policy "Allow all access to patients" on patients for all using (true) with check (true);
